- .env
- src/routes.tsx
Closes #47.
Moves the plugin URL to an environment variable.
> Make plugin url an environment variable

- .github/workflows/cypress_tests.yml
- cypress/component/HomePage.cy.tsx
- cypress/component/Instrument.cy.tsx
- tsconfig.json
Closes #19.
Adds a workflow which runs the Cypress tests to see if they pass.
> Add Cypress workflow

- src/Instrument.styles.tsx
- src/Instrument.tsx
Closes #70, closes #46.
- Adds full URL for instrument details page.
- Adds an outline to the Live Reduction and Reduction History buttons.
> Improve instrument card readability

- src/ReductionHistory.tsx
- yarn.lock
Closes #44, closes #46.
Merges the reduction status and experiment number columns into a single column. The reduction status is now displayed as an icon with a hoverable tooltip which details the reduction status message.
> Add reduction status msg to table

- .env
- src/ReductionHistory.tsx
Closes #138, closes #141.
1. Change env variables to point towards relevant IPs.
2. Run the app and click the view button for one of the reduction output files.
> Connect view button to the data viewer

- container/default.json
Closes #65, closes #64.
1. Replace SciGateway's `public/res` folder with the contents of this repo's `container` folder.
2. Run the web app.
3. See if clicking the footer links does anything. Also check if the accessibility statement page reads **correct**.
> Update footer links

- .github/workflows/build-push-action.yml
> Initial CD prototype

- src/InstrumentData.ts
- src/Instruments.tsx
Closes #164, closes #131.
1. Instruments page should feel more responsive and fixes incorrect styling.
2. Data viewer button is removed.
3. Added favourite instrument star button logic (might be something worth implementing fully?)
> Make instruments page more responsive and fix styling

- public/index.html
- src/App.tsx
Closes None, part of an epic than spans multiple services.
Add a new route called /healthz that simply has "ok" displayed.
> Add health check

- README.md
Closes #17.
Adds some basic information on how to get the frontend downloaded and ready for development.
> Update README and add developer instructions

- README.md
Closes #218.
Adds a section in the README about using containers for development. Also used more concise language throughout.
> Add README note about containers

- .env
> Add env values

- container/index.html
- src/App.tsx
- src/usePageTracking.js
Closes #196.
Adds a Google Analytics tag to `index.html` and a page tracking hook.
> Add ga tag

- container/index.html
> Use new tag

- src/ReductionHistory.tsx
- src/ValueEditor.tsx
Closes None, part of overall work to facilitate API changes
Just changing the endpoints that the frontend calls in the API
> Update endpoints to reflect new API changes

- src/HomePage.tsx
- src/Jobs/JobsBase.tsx
Closes #335.
Migrates to Grid2 in files that used the component.
> Switch to Grid2 component

- src/ConfigSettings/ConfigSettingsGeneral.tsx
- src/Jobs/JobsAll.tsx
- src/Jobs/JobsGeneral.tsx
Closes #197.
Adds missing dev checks to API calls.
> Add missing dev checks to API calls

- src/Jobs/JobsBase.tsx
Closes #368.
Adds a fixed scrollbar to the run table. Stops the contents reformatting in circumstances where a scrollbar is needed.
> Add fixed scrollbar

- src/Jobs/JobsBase.tsx
Closes #381 
This PR will add:
- The Job start and Job end columns to the job table
> Add Job start and end columns to job table

- src/Jobs/JobsBase.tsx
Closes #407.
Fixes bug where expanded row data wasn't filling the entire table width.
> Update base column number

- .github/workflows/build-push-action.yml
- src/App.tsx
- src/ConfigSettings/ConfigSettingsGeneral.tsx
- src/HomePage.tsx
- src/Jobs/JobsAll.tsx
- src/Jobs/JobsBase.tsx
- src/Jobs/JobsGeneral.tsx
- src/ValueEditor.tsx
- src/api.ts
Closes #238 
- Creates single axios instance to be reused
- Remove the previous api urls spread around
- handles token expiry without page refresh
- removed some unused props
> Stale token refresh

- src/Jobs/JobsAll.tsx
Closes #414.
Adds underlining to the values in the Instrument column in the reduction table.
> Add underline for instrument column

- src/Jobs/JobsAll.tsx
Closes #427.
Fixes the table linking to 404 pages.
> Fix Link routing

- src/App.tsx
- src/ConfigSettings/ConfigSettingsLOQ.tsx
- src/ConfigSettings/FileUploader.tsx
- src/GlobalStyles.tsx
- src/Instruments.tsx
- src/Jobs/JobsAll.tsx
- src/Jobs/JobsGeneral.tsx
Closes #377.
Adds code comments to important files that were missing code context.
> Add code comments

- src/ConfigSettings/ConfigSettingsGeneral.tsx
- src/ConfigSettings/ConfigSettingsSANS2D.tsx
- src/Jobs/JobsBase.tsx
- src/Jobs/JobsGeneral.tsx
Closes #442, closes #449.
Adds a config page for SANS2D that provides the same functionality as the LOQ config page.
> Add config page for SANS2D

- src/Instruments.tsx
Closes #452.
Makes starred instruments persistent after navigating away from page.
> Add local storage for favorites

- src/components/jobs/Row.tsx
Closes #350, closes #479
Enables the download button for file downloading.
Fixes bug with output handling function receiving null type.
> Enable download button

- src/components/jobs/JobTableHead.tsx
Closes # 
Makes the filename column wider so the value can actually be seen in full.
> Adjust column width values

- src/components/configsettings/ConfigSettingsGeneral.tsx
- src/components/configsettings/ConfigSettingsIRIS.tsx
- src/components/configsettings/ConfigSettingsOSIRIS.tsx
- src/components/configsettings/InstrumentConfigDrawer.tsx
- src/pages/JobsPage.tsx
Closes #491, closes #492.
Adds config files for IRIS and OSIRIS.
Allow for suitable dictionary handling in the simple specification editor.
> Add IRIS and OSIRIS configs

- src/components/jobs/Filters.tsx
- src/components/jobs/JobTable.tsx
- src/components/jobs/JobTableHead.tsx
- src/components/jobs/Row.tsx
- src/pages/JobsPage.tsx
Closes #456.
Adds a button for bulk rerunning filtered jobs.
> Add bulk rerun button to filters section

- src/components/jobs/Row.tsx
- src/lib/timezone.ts
Closes #520
Using our locale timezone instead of UTC of GMT +0 for everything
> Add new function for BST into Row.tsx

- .env
- README.md
- index.html
- package.json
- src/components/jobs/Row.tsx
- src/index.css
- src/index.tsx
- src/lib/api.ts
- src/routes.tsx
- src/vite-env.d.ts
- vite.config.ts
- yarn.lock
Closes #518.
Switches from using Craco to Vite.
Should be able to build and run through SciGateway same as before without any JSON config files changes.
> Vite migration

- src/components/jobs/Row.tsx
Closes #549 
Swap out the job id number for the experiment number
> Change job ID for experiment number
